version: 2

models:
  - name: http_events
    description: "Parsed Envoy proxy logs from production"
  # - name: http_events_bytes_sent
  #   description: "Sum of total bytes sent per request method in the Envoy proxy logs"
  # - name: events_count
  #   description: "Sample aggregation model"
